"""Original real-CPU EC..EF diagnostic; static storage is not a running RTC.

Default acceptance requires elapsed time to advance seconds. --characterize
instead reproduces the current missing-tick defect explicitly, not RTC PASS.
No private ROM, injected RAM or forced timer is used.
"""
import argparse
import hashlib
import json
import pathlib
import shutil
import subprocess
from z80_fixture import Program


DATE = bytes((0x31, 0xC6, 0x99))
TIME = bytes((0x12, 0x34, 0x56))


def fixture():
    p = Program()
    p.emit(0xF3)
    p.word(0x31, 0xFFFF)
    p.word(0x01, 0x1A03)
    p.emit(0x3E, 0x82, 0xED, 0x79)
    for i, value in enumerate(b'RTC0'):
        p.store(0xF000 + i, value)
    serial = 0

    def send(value):
        nonlocal serial
        serial += 1
        label = f'write-ready-{serial}'
        p.word(0x01, 0x1A01)
        p.label(label)
        p.emit(0xED, 0x78, 0xE6, 0x40)
        p.jump(0xC2, label)
        p.word(0x01, 0x1900)
        p.emit(0x3E, value, 0xED, 0x79)

    def read(command, address):
        nonlocal serial
        send(command)
        for i in range(3):
            serial += 1
            label = f'read-ready-{serial}'
            p.word(0x01, 0x1A01)
            p.label(label)
            p.emit(0xED, 0x78, 0xE6, 0x20)
            p.jump(0xC2, label)
            p.word(0x01, 0x1900)
            p.emit(0xED, 0x78)
            p.word(0x32, address + i)

    for command, values in ((0xEC, DATE), (0xEE, TIME)):
        for value in (command, *values):
            send(value)
    read(0xED, 0xF010)
    read(0xEF, 0xF013)
    p.store(0xF003, ord('1'))
    # 4 * 65535 * (6+4+4+10) T states > 1.57 seconds at the native 4 MHz.
    # IRQ is disabled but the independently executing MR16 must keep time.
    p.emit(0x16, 4)  # LD D,4
    p.label('delay-outer')
    p.word(0x21, 0xFFFF)
    p.label('delay-inner')
    p.emit(0x2B, 0x7C, 0xB5)
    p.jump(0xC2, 'delay-inner')
    p.emit(0x15)
    p.jump(0xC2, 'delay-outer')
    read(0xED, 0xF020)
    read(0xEF, 0xF023)
    p.store(0xF003, ord('2'))
    p.label('done')
    p.emit(0x76)
    p.jump(0xC3, 'done')
    return p.finish()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('executable', type=pathlib.Path)
    parser.add_argument('--output', type=pathlib.Path, required=True)
    parser.add_argument('--timeout', type=float, default=600)
    parser.add_argument('--characterize', action='store_true')
    args = parser.parse_args()
    if args.timeout <= 0:
        parser.error('positive timeout required')
    exe = args.executable.resolve()
    folder = args.output.resolve()
    folder.mkdir(parents=True, exist_ok=False)
    frozen = folder / 'Vtop'
    sha = lambda path: hashlib.sha256(path.read_bytes()).hexdigest()
    original = sha(exe)
    shutil.copy2(exe, frozen)
    assert sha(frozen) == original
    rom = folder / 'rtc.bin'
    rom.write_bytes(fixture())
    command = [str(frozen), '--cycles', '70400000', '--rom', str(rom), '--dump', str(folder / 'cpu')]
    result = subprocess.run(command, capture_output=True, text=True, timeout=args.timeout)
    (folder / 'cpu.stdout').write_text(result.stdout)
    (folder / 'cpu.stderr').write_text(result.stderr)
    assert result.returncode == 0, result.stderr
    report = json.loads(result.stdout.splitlines()[-1])
    memory = (folder / 'cpu.ram').read_bytes()
    early, late = memory[0xF010:0xF016], memory[0xF020:0xF026]
    evidence = {'command': command, 'returncode': result.returncode, 'report': report,
                'executable_sha256': original, 'program_sha256': sha(rom),
                'collector_sha256': sha(pathlib.Path(__file__).resolve()),
                'early_date_time': early.hex(), 'late_date_time': late.hex(),
                'characterization_only': args.characterize, 'rtc_accepted': False}
    provenance = folder / 'provenance.json'
    provenance.write_text(json.dumps(evidence, indent=2) + '\n')
    assert report['machine'] == 'sharpx1' and report['sys_hz'] == 32000000
    assert report['video_hz'] == 28571428
    for flag in ('turbo_foundation', 'turbo_video_master', 'turbo_dma', 'turbo_dma_irq',
                 'turbo_kanji', 'turbo_fm_cpu', 'z_palette_cpu_experiment', 'z_video_experiment',
                 'z_multimode_experiment', 'z_internal8_experiment', 'z_text_cpu_experiment'):
        assert report[flag] is False, f'not ordinary machine: {flag}'
    assert report['time_ps'] == 2200000000000 and report['halted']
    assert report['disk_requests'] == report['disk_writes'] == report['ps2_bytes_sent'] == 0
    assert memory[0xF000:0xF004] == b'RTC2', 'CPU mailbox diagnostic did not finish'
    assert early == DATE + TIME, 'real CPU set/read protocol differs from generated bytes'
    assert late[:3] == DATE and late[3:5] == TIME[:2], 'date/hour/minute unexpectedly changed'
    assert sha(exe) == sha(frozen) == original
    print(json.dumps(evidence), flush=True)
    if args.characterize:
        assert late == early, 'missing-tick defect not reproduced; run ordinary acceptance'
        print('REPRODUCED: real CPU date/time set/read works but seconds remain static after >1.57 seconds; RTC acceptance OPEN', flush=True)
    else:
        assert late[5] in (0x57, 0x58), 'RTC does not advance after elapsed native CPU delay'
        evidence['rtc_accepted'] = True
        provenance.write_text(json.dumps(evidence, indent=2) + '\n')
        print('PASS: real CPU elapsed seconds with EC..EF set/read; calendar/reset/persistence/pin acceptance separate', flush=True)


if __name__ == '__main__':
    main()
